[build-system]
requires = ["pytoml>=0.1", "scons", "enscons"]
build-backend = "enscons.api"

[tool.enscons]
name="enscons"
version="0.8.1"
packages=['enscons']
install_requires=['scons', 'pytoml>=0.1', 'setuptools', 'wheel']
description="Tools for building Python packages with SCons"
description_file="README.rst"
license="MIT"
classifiers=[
  "Programming Language :: Python :: 2.7",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.4",
  "Programming Language :: Python :: 3.5",
  "Programming Language :: Python :: 3.6",
]
keywords=["packaging", "wheel"]
author="Daniel Holth"
author_email="dholth@fastmail.fm"
url="https://bitbucket.org/dholth/enscons"

[tool.enscons.entry_points]
console_scripts = ["setup2toml = enscons.setup2toml:main"]

[tool.enscons.extras_require]
doc = ['sphinx']
cli = ['click']
